inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-rails

AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - vendor/bundle/**/*

Style/Documentation:
  Enabled: false

