# examples:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_cleanup_with_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day

production:
  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: every hour at minute 12
  send_due_date_reminder:
    class: SendDueDateReminderJob
    queue: background
    schedule: "0 6 * * *"
  update_due_date:
    class: UpdateDueDateJob
    queue: background
    schedule: "0 1 1 * *"

development:
  send_due_date_reminder:
    class: SendDueDateReminderJob
    queue: background
    schedule: "0 6 * * *"
  update_due_date:
    class: UpdateDueDateJob
    queue: background
    schedule: "0 1 1 * *"

